//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string Name { get; set; }
        public string Password { get; set; }
        public int CNIC { get; set; }
        public string Email { get; set; }
        public int Contact_No { get; set; }
        public string Home_Address { get; set; }
    }
}
