//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Store_Inventory_SystemEntities : DbContext
    {
        public Store_Inventory_SystemEntities()
            : base("name=Store_Inventory_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Add_To_Cart> Add_To_Cart { get; set; }
        public virtual DbSet<Manager_Login> Manager_Login { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    }
}
